supabase/edge-runtime

crates/base/src/edge_runtime.rs
crates/base/src/worker_ctx.rs

This is based on #51. Had to make a couple of changes to work it correctly with current main.

fix: correctly enforce max duration

---

crates/base/src/edge_runtime.rs
crates/base/src/js_worker/mod.rs
crates/base/src/js_worker/types.rs
crates/base/test_cases/heap_limit/index.ts
crates/base/test_cases/infinite_loop/index.ts
crates/base/test_cases/infinite_promises/index.ts
crates/base/test_cases/resolve_promise_after_timeout/index.ts
crates/base/test_cases/resolve_promise_before_timeout/index.ts
crates/base/test_cases/unresolved_promise/index.ts
examples/infinite_loop/index.ts

This PR introduces tests for the `edge-runtime`, both user and main behavior.

Integrate tests

---

crates/base/src/edge_runtime.rs
crates/base/src/server.rs
crates/base/src/worker_ctx.rs
crates/sb_core/http_start.rs
crates/sb_core/js/bootstrap.js
crates/sb_core/net.rs
crates/sb_worker_context/essentials.rs
crates/sb_workers/lib.rs
crates/sb_workers/user_workers.js
examples/main/index.ts

* Refactor handling of incoming requests to improve performance.
* When a worker is a shutdown, the pool gets notified so it knows not to route future requests to that worker.
* Updated the`examples/main` to reuse existing workers.

Refactor connection handling

---

crates/base/src/edge_runtime.rs
crates/base/test_cases/main/index.ts
crates/base/test_cases/oak/index.ts
crates/sb_core/js/bootstrap.js
crates/sb_core/js/permissions.js
crates/sb_core/lib.rs
examples/oak/index.ts
scripts/run.sh

This PR introruces:
- Fixing the oak issue #60 
- Catching the error inside the EdgeResult 
- Tests
- Permissions exposed

Fix oak #60

---

crates/base/src/edge_runtime.rs

fix clippy

---

Cargo.lock
Cargo.toml
crates/base/Cargo.toml
crates/base/src/edge_runtime.rs
crates/flaky_test/Cargo.toml
crates/flaky_test/lib.rs
crates/flaky_test/tests/tests.rs

This PR introduces a procedural attribute to repeat async tests up to 3 times.

Flaky test attr

---

.github/workflows/release.yml

chore: downgrade release notes generator dep

---

examples/axios/index.ts

Adding an example for using Axios in edge functions. I couldn't reproduce #54 with the example code.

chore: added Axios example

---

crates/sb_core/js/bootstrap.js
crates/sb_core/js/denoOverrides.js
crates/sb_core/js/errors.js
crates/sb_core/js/fieldUtils.js
crates/sb_core/js/http.js
crates/sb_core/js/promises.js
crates/sb_core/lib.rs

Refactoring bootstrap files, import and utilities

---

crates/base/src/edge_runtime.rs
crates/base/src/errors_rt.rs
crates/base/src/lib.rs
crates/base/test_cases/tls_invalid_data/index.ts
crates/base/tests/oak_user_worker_tests.rs
crates/base/tests/tls_invalid_data_tests.rs
crates/sb_core/js/errors.js

Adding error reader

---

crates/base/test_cases/empty-response/index.ts
crates/base/tests/null_body_status_null_body_tests.rs
crates/base/tests/oak_user_worker_tests.rs
crates/sb_core/js/errors.js
crates/sb_workers/lib.rs
crates/sb_workers/user_workers.js
examples/empty-response/index.ts

Fixes https://github.com/supabase/cli/issues/1071

Fix body null for null status

---

crates/base/src/commands.rs
crates/base/src/lib.rs
crates/base/src/macros/mod.rs
crates/base/src/macros/test_macros.rs
crates/base/src/server.rs
crates/base/test_cases/readable-stream-resp/index.ts
crates/base/tests/custom_readable_response_tests.rs
crates/cli/src/main.rs

Adds integration test macros with signals

Chroe: Unit test for readable streams + signals + integration test macro

---

crates/sb_core/js/bootstrap.js
crates/sb_core/js/denoOverrides.js

Fixes #104 
Also, add Deno.refTimer and Deno.unrefTimer

Add structuredClone & ref/unrefTimers

---

.prettierrc
crates/base/src/server.rs
crates/base/src/worker_ctx.rs
crates/base/test_cases/boot_err_user_worker/index.ts
crates/base/tests/main_worker_tests.rs
crates/base/tests/user_worker_tests.rs
deno.json
examples/main/index.ts

Handle exceptions thrown during module evaluation phase of user workers.
Unrelated to the change: I added .prettierrc to format JS files.

Handle user worker exceptions

---

crates/base/src/server.rs
examples/main/index.ts

Removed the default health check endpoint. Recommended approach would be to implement a custom health check endpoint in main function.

feat: remove health check endpoint

---

crates/base/src/edge_runtime.rs
crates/base/src/worker_ctx.rs
crates/sb_worker_context/events.rs

Introduces events for:
- uncaughtException
- memoryLimit
- timeLimit

Uncaught exception, memory & time limit events

---

crates/base/src/worker_ctx.rs

Name the worker threads so it's easy to debug. Eg: `top -H -p pid` will show all threads run by edge runtime.

chore: add names to worker threads

---

crates/base/src/edge_runtime.rs
crates/sb_core/js/denoOverrides.js
crates/sb_os/os.js

Deno.version following Deno's deploy result

Deno.version, networkInterfaces following Deno's deploy result

---

crates/base/src/worker_ctx.rs

Fixes #121 
Modified request handlers to use separate tokio tasks.

fix: handling concurrent requests to workers

---

crates/flaky_test/lib.rs
crates/sb_core/js/bootstrap.js
crates/sb_core/js/navigator.js
crates/sb_core/lib.rs

Add `navigator` global to the runtime

fix: add navigator global

---

.github/workflows/release.yml

Trying to fix the GitHub release. Upgrading semantic-release as [suggested here](https://github.com/cycjimmy/semantic-release-action/issues/159#issuecomment-1549679103)

fix: upgrade semantic release

---

Cargo.lock
Cargo.toml
README.md
crates/base/Cargo.toml
crates/base/src/deno_runtime.rs
crates/base/src/lib.rs
crates/base/src/server.rs
crates/base/src/worker_ctx.rs
crates/base/tests/import_map_tests.rs
crates/base/tests/main_worker_tests.rs
crates/base/tests/null_body_status_null_body_tests.rs
crates/base/tests/oak_user_worker_tests.rs
crates/base/tests/tls_invalid_data_tests.rs
crates/base/tests/user_worker_tests.rs
crates/base/tests/worker_boot_tests.rs
crates/cpu_timer/Cargo.toml
crates/cpu_timer/src/lib.rs
crates/cpu_timer/src/timerid.rs
crates/module_fetcher/Cargo.toml
crates/sb_worker_context/Cargo.toml
crates/sb_worker_context/essentials.rs
crates/sb_worker_context/events.rs
crates/sb_workers/lib.rs
crates/sb_workers/user_workers.js
examples/event-manager/index.ts
examples/hello-world/index.ts
examples/main/index.ts
examples/wasm-stream/index.ts

This PR introduces way to measure CPU time used by user workers and enforce max CPU time use.
Also, includes some refactoring to move all enforcements into a supervisor thread.

Measure CPU time used by a worker

---

crates/base/src/worker_ctx.rs
crates/sb_worker_context/events.rs
crates/sb_workers/event_worker.js
examples/event-manager/index.ts
examples/main/index.ts

Send the CPU time used as an event to the event log. Marking this PR as a `feat` since I missed to tag the previous one and want to make a new release.

feat: log CPU time used as an event

---

crates/base/src/deno_runtime.rs

Support providing v8 flags via environment variables. (eg: `V8_FLAGS="--prof --logfile=edge.log" ./scripts/run.sh`)

fix: configure v8 flags via env variables

---

Cargo.lock
crates/base/src/worker_ctx.rs
crates/sb_workers/Cargo.toml
crates/sb_workers/lib.rs
examples/main/index.ts

Print to stderr if no logger is defined.

fix: print to stderr when logger is not available

---

crates/base/build.rs
crates/base/src/deno_runtime.rs
crates/base/src/server.rs
crates/cli/src/logger.rs
crates/cli/src/main.rs
crates/module_fetcher/src/file_fetcher.rs
crates/module_fetcher/src/npm/resolution/graph.rs
crates/sb_core/permissions.rs
crates/sb_worker_context/essentials.rs
crates/sb_workers/lib.rs
crates/sb_workers/user_workers.js
examples/main/index.ts

Provides a new option to disable net access in the user worker.

Option to disable net access in user workers

---

examples/main/index.ts

fix: main function example

---

crates/sb_core/net.rs

This should fix panics if unix channel receiver is not available.

fix: do not panic if unix rx is not available

---

README.md

chore: run.sh already has start main-service defined

---

crates/sb_core/js/denoOverrides.js
examples/logger-stdout/index.ts

Fixes #162 by integrating `Deno.stdout` and isitty

Deno.stdout integration

---

crates/sb_core/js/denoOverrides.js
crates/sb_core/js/http.js
examples/serve/index.ts

Include Deno.serve functionality based on serveHttp op. Fixes #161

feat: Include Deno.serve functionality based on serveHttp op

---

crates/module_fetcher/src/args/config_file.rs
crates/module_fetcher/src/cache/http_cache/local.rs
crates/module_fetcher/src/file_fetcher.rs
crates/module_fetcher/src/npm/resolvers/global.rs
crates/module_fetcher/src/npm/resolvers/local.rs
crates/module_fetcher/src/npm/resolvers/mod.rs
crates/module_fetcher/src/util/v8.rs
crates/node/global.rs
crates/node/lib.rs
crates/node/ops/crypto/x509.rs
crates/node/resolution.rs

PR fixes the cargo fmt and clippy errors.

chore: fix cargo fmt & clippy errors

---

crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/rt_worker/worker_pool.rs
crates/base/test_cases/main_with_abort/index.ts
crates/base/tests/main_worker_tests.rs
crates/sb_workers/lib.rs
crates/sb_workers/user_workers.js
examples/main/index.ts
examples/read-body/index.ts
examples/stream/index.ts

This PR adds the option to abort user worker requests.
Also, updated the implementation to correctly close the response bodies for null-body responses.

feat: Option to abort user worker requests

---

crates/base/src/deno_runtime.rs

It will be available to access within functions as `SB_EXECUTION_ID`.

fix: expose execution_id as a environment variable

---

crates/base/src/deno_runtime.rs
crates/base/test_cases/array_buffers/index.ts
crates/sb_core/external_memory.rs
crates/sb_core/lib.rs

Switch to use a custom array buffer allocator, which can enforce limits on the max size of array buffer.

feat: enforce limits on array buffer allocations

---

crates/sb_core/js/bootstrap.js

Bug fix
Fixes https://github.com/supabase/cli/issues/1963

fix: calling `core.setBuildInfo` is necessary

---

crates/base/src/deno_runtime.rs
crates/sb_core/js/bootstrap.js

Bug fix
Packages that directly depend on `std@0.132.0`, such as `postgres.js`, will call `internals.warnOnDeprecatedApi` in some cases.
This PR adds `warnOnDeprecatedApi` to the `internals` namespace for this purpose.
As with Deno upstream, you can disable this warning via an environment variable or get detailed logs.
* DENO_NO_DEPRECATION_WARNINGS=1: Disables the deprecation warnings
* DENO_VERBOSE_WARNINGS=1: Prints a more detailed deprecation warnings
This issue was reported in [a comment in the Discussion #17258](https://github.com/orgs/supabase/discussions/17258#discussioncomment-8534676)
Reported-By: @leblancmeneses

fix: introduce `internals.warnOnDeprecatedApi` for Deno backward compatibility

---

Cargo.lock
crates/base/Cargo.toml

Reverts supabase/edge-runtime#287

Revert "chore(deps): bump tls-listener from 0.9.1 to 0.10.0"

---

crates/sb_ai/ai.js
examples/supa-ai/index.ts

This PR extends `Supabase.ai` API to use an optional Ollama server to delegate model inferences.
The environment variable `AI_INFERENCE_API_HOST`  must be set with the host URL of your Ollama server (eg: `http://127.0.0.1:11434`)

Ollama support for AI inference

---

crates/sb_ai/ai.js

This PR disables Ollama based inferencing if the host name environment variable is not set.

fix: Handle when Ollama host is not set

---

crates/base/src/server.rs
crates/sb_core/lib.rs

Bug fix
https://github.com/supabase/edge-runtime/actions/runs/8776826527/job/24080906109

fix: remove `debug_assertions` attribute

---

crates/cli/src/main.rs

chore: apply `rustfmt`

---

crates/base/src/server.rs

do not process `SignalKind::window_change()]`

fix: do not shutdown server on resize

---

DEVELOPERS.md
crates/cli/Cargo.toml
crates/cli/src/main.rs
scripts/run.sh

Feature
This PR introduces a feature flag to allow the logging backend to be replaced with `tracing-subscriber`, which provides better information.

feat: allow replacing logging backend as `tracing-subscriber` via feature flag

---

crates/cli/src/flags.rs

Enhancement
This PR updates the descriptions of some cli flags (showing default values)

fix: update cli flag description

---

crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/supervisor/strategy_per_request.rs
crates/base/src/rt_worker/supervisor/strategy_per_worker.rs
crates/base/src/rt_worker/worker.rs

Bug fix
If a worker fails to boot while the inspector feature is enabled, the upstream inspector implementation may panic and crash the runtime (due to v8::Abort).
This PR prevents the panic from propagating to the runtime and fixes it so that the failed worker can be properly cleaned up after the panic.

fix(base): add guards to cleanup logics

---

Cargo.lock
Cargo.toml
crates/base/src/rt_worker/supervisor/mod.rs
crates/base/src/rt_worker/supervisor/strategy_per_request.rs
crates/base/src/rt_worker/supervisor/strategy_per_worker.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/event_worker/Cargo.toml
crates/event_worker/events.rs

Enhancement
Before
```
{
timestamp: "2024-06-14T00:35:08.578Z",
event_type: "Shutdown",
event: [Object: null prototype] {
reason: [Object: null prototype] {
Memory: [Object: null prototype] { limited_by: "mem_check" } // 👈
},
cpu_time_used: 74,
memory_used: [Object: null prototype] {
total: 67685841,
heap: 6460736,
external: 61225105,
mem_check_captured: [Object: null prototype] {
current: [Object: null prototype] {
totalHeapSize: 8626176,
totalHeapSizeExecutable: 262144,
totalPhysicalSize: 7131136,
totalAvailableSize: 61063776,
totalGlobalHandlesSize: 24576,
usedGlobalHandlesSize: 18976,
usedHeapSize: 6460736,
mallocedMemory: 6460736,
externalMemory: 61225105,
peakMallocedMemory: 139480
},
exceeded: true
}
}
},
metadata: [Object: null prototype] {
service_path: "./examples/serve", …
```

fix: simplify the shutdown reason due to the memory limit of the event record

---

crates/base/tests/integration_tests.rs

chore: fix flaky integration test

---

crates/base/src/rt_worker/supervisor/strategy_per_worker.rs

Bug fix
It looks like the early retire signalling lines were removed during the refactoring of the supervisor 😓
This caused a regression that allowed incoming requests to be accepted by workers with insufficient wall clock time or cpu time remaining.
Slack: [link](https://supabase.slack.com/archives/C06FZ5JP1D1/p1720390519778229?thread_ts=1720207373.152669&cid=C06FZ5JP1D1)
cc @inian

fix: missing early retire signal

---

Cargo.lock
crates/sb_ai/Cargo.toml
crates/sb_ai/lib.rs

Bug fix
This PR fixes an issue where the cpu time used in the inference task of the gte model is not properly tracked.
> Note: All future implementations should take the same approach as this PR for tracking correct CPU time when trying to perform CPU-intensive tasks outside of the v8 callstack.

fix(sb_ai/gte): cpu time should be accumulated correctly

---

crates/sb_core/js/bootstrap.js

Bug fix
* Expose [CompressionStream](https://developer.mozilla.org/en-US/docs/Web/API/CompressionStream) API
* Expose [DecompressionStream](https://developer.mozilla.org/en-US/docs/Web/API/DecompressionStream) API
This issue was reported in [Discussion #28092](https://github.com/orgs/supabase/discussions/28092)
Reported-By: @jakeklassen

fix(sb_core): expose web compression/decompression stream API

---

crates/base/src/inspector_server.rs

Bug fix
Connections for inspector sessions should be upgradeable.
Note:
This regression was made during the recent deno upgrade, so previous revisions are unaffected.

fix(base): connections for inspector sessions should be upgradeable to the websocket

---

crates/sb_graph/eszip_migrate.rs

Bug fix
```rust
// eszip_migrate.rs:310
// Wrong
let Ok(v1_dir) = rkyv::from_bytes::<v1::Directory>(&vfs_mod_data) else {
// Should be
let Ok(v1_dir) = rkyv::from_bytes::<Option<v1::Directory>>(&vfs_mod_data) else {
```

fix(sb_graph): failed to deserialize in the v1.1 migration phase due to specifying the wrong type

---

crates/node/ops/http2.rs

fix(node): mitigate denoland/deno#24678

---

Cargo.lock

Chore
Resolves https://github.com/supabase/edge-runtime/security/dependabot/38

chore: update `Cargo.lock`

---

crates/base/src/deno_runtime.rs

Bug fix
We need to find the cause of the intermittent segmentation fault after the Deno upgrade PR, so I am reverting some changes that were added to that PR.

fix(base): partial revert some changes that were introduced from deno upgrade PR

---

crates/base/src/deno_runtime.rs
crates/base/test_cases/issue-420/index.ts
crates/base/tests/integration_tests.rs

fix(base): pass import meta resolve callback when initialize `JsRuntime`

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Bug fix
Install deno correctly and set the PATH environment variable correctly.

chore(devcontainer): install deno properly

---

crates/base/test_cases/eszip-js/npm-supabase-js/index.js
crates/base/test_cases/eszip-js/serve-js/index.js
crates/base/test_cases/main_eszip/index.ts
crates/base/test_cases/serve-declarative-style-js/index.js
crates/base/test_cases/serve-js/index.js
crates/base/tests/integration_tests.rs
examples/serve-declarative-style-js/index.js
examples/serve-js/index.js

Chore
This is just to clarify that the edge runtime can also be used JavaScript as an entry point.

chore: make sure that we can use javascript as an entrypoint

---

crates/cli/src/flags.rs

fix(cli): `--static` flag could not be used multiple times

---

crates/sb_core/js/bootstrap.js

Bug fix
* Expose [MessageChannel](https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel) API

fix(sb_core): expose web MessageChannel API

---

.github/workflows/release.yml
Dockerfile

Bug fix
Slack: https://supabase.slack.com/archives/C03S3SW9485/p1731388085254969?thread_ts=1725359881.785819&cid=C03S3SW9485

fix(ci): release workflow failure

---

Cargo.lock
crates/base/Cargo.toml
crates/base/src/deno_runtime.rs
crates/base/test_cases/issue-456/index.ts
crates/base/test_cases/main/index.ts
crates/base/tests/integration_tests.rs
crates/sb_module_loader/standalone/standalone_module_loader.rs

Bug fix
Fixes #456 
Reported-by: @0x5457

fix(base): checking more strictly whether source map inlining is possible

---

deno.json
ext/core/js/bootstrap.js
ext/core/js/namespaces.js
ext/core/lib.rs
types/global.d.ts

Bug fix
Bring back the missing `Supabase` namespace.

fix(ext/core): missing `Supabase` namespace

---

crates/base/test_cases/supabase-ai/index.ts
crates/base/tests/integration_tests.rs

Miscellaneous
Adds a test coverage for `Supabase.ai`

chore(base): add an integration test for `Supabase.ai`

---

ext/core/js/namespaces.js

Expose Supabase API to be used in main worker.

fix: expose Supabase namespace to main worker

---

crates/base/src/deno_runtime.rs
crates/fs/impl/deno_compile_fs.rs
crates/fs/impl/static_fs.rs
crates/fs/impl/virtual_fs.rs
crates/fs/lib.rs
crates/fs/rt.rs
crates/graph/lib.rs
crates/module_loader/standalone/mod.rs
examples/serve-html/index.ts

1. If an entrypoint path is defined, use that as the root for static files
2. Don't spawn IO tasks in the current runtime

Fix static file paths and race conditions

---

crates/graph/lib.rs

Enhancement
Make read barrier routine more robust.

fix(graph): make barrier more robust

---

ext/node/polyfills/process.ts

Bug fix
cherry picked from upstream pr https://github.com/denoland/deno/pull/27891
closes #484

fix(ext/node): set process.env as own property

---

.github/workflows/ci.yml
Cargo.lock
ext/ai/Cargo.toml
ext/ai/lib.rs

This adds github actions to use Traupalin to generate code coverage report and send it to Coveralls.

Code coverage

---

.github/workflows/ci.yml

Chore
Make CI run when PR is merged into develop branch.

chore: run CI when the PR merged into develop branch

---

crates/deno_facade/emitter.rs
crates/deno_facade/eszip/migrate.rs
crates/deno_facade/eszip/mod.rs
crates/deno_facade/eszip/vfs.rs
crates/deno_facade/metadata.rs
crates/deno_facade/module_loader/standalone.rs
crates/fs/impl/virtual_fs.rs
crates/fs/lib.rs
deno/lib.rs
deno/npm/mod.rs
deno/standalone/binary.rs
examples/commonjs/index.js
examples/commonjs/package.json

Feature
This PR makes it possible to load commonjs.
Please refer to `examples/commonjs`

feat: support loading the commonjs

---

crates/base/test_cases/commonjs-workspace/cat/index.js
crates/base/test_cases/commonjs-workspace/cat/package.json
crates/base/test_cases/commonjs-workspace/dog/index.js
crates/base/test_cases/commonjs-workspace/dog/package.json
crates/base/test_cases/commonjs-workspace/index.js
crates/base/test_cases/commonjs-workspace/package.json
crates/base/test_cases/commonjs-workspace/say/index.js
crates/base/test_cases/commonjs-workspace/say/package.json
crates/base/test_cases/main/index.ts
crates/base/test_cases/workspace/cat/deno.json
crates/base/test_cases/workspace/cat/mod.ts
crates/base/test_cases/workspace/deno.json
crates/base/test_cases/workspace/dog/deno.json
crates/base/test_cases/workspace/dog/mod.ts
crates/base/test_cases/workspace/index.ts
crates/base/test_cases/workspace/say/deno.json
crates/base/test_cases/workspace/say/mod.ts
crates/base/test_cases/workspace/wolf/deno.json
crates/base/test_cases/workspace/wolf/mod.ts
crates/base/tests/integration_tests.rs

Chore
Closes FUNC-172
Ref: https://github.com/supabase/cli/issues/3093

chore: add integration tests for deno/commonjs workspace feature

---

crates/base/test_cases/supabase-issue-29583/index.ts
crates/base/tests/integration_tests.rs

Chore
Closes FUNC-181
~Blocked by #507~

chore: add an integration test for supabase/supabase#29583

---

crates/deno_facade/eszip/migrate.rs

Bug fix
This one small typo caused the edge runtime to get stuck indefinitely when creating a function.
ouch

fix(deno_facade): a typo in migration function

---

crates/base/src/runtime/mod.rs
crates/base/src/worker/supervisor/strategy_per_worker.rs
crates/base/test_cases/issue-func-205/index.ts
crates/base/test_cases/main/index.ts
crates/base/tests/fixture/testdata/fdqdoblxppxtigtdfhbh_c1bfd9f7-0bdc-4c1e-9794-8cc8160e4069_12.out.snapshot
crates/base/tests/fixture/testdata/tzqeounajgztphucxgjw_537a54e4-f242-48f4-9563-4717d6fd22b3_2.out.snapshot
crates/base/tests/fixture/testdata/tzqeounajgztphucxgjw_7e659cb3-e8fa-4845-83ad-26bbd798b3ab_2.out.snapshot
crates/base/tests/integration_tests.rs
ext/event_worker/events.rs

Backport
See the commit history.

[develop] backports

---

crates/base/tests/fixture/testdata/fdqdoblxppxtigtdfhbh_c1bfd9f7-0bdc-4c1e-9794-8cc8160e4069_12.out.snapshot
crates/base/tests/fixture/testdata/tzqeounajgztphucxgjw_537a54e4-f242-48f4-9563-4717d6fd22b3_2.out.snapshot
crates/base/tests/fixture/testdata/tzqeounajgztphucxgjw_7e659cb3-e8fa-4845-83ad-26bbd798b3ab_2.out.snapshot

Bug fix
Update eszip migration snapshots.

chore: update eszip migration snapshots

---

.github/workflows/release.yml

Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.

chore: bump ubuntu version

---

.github/workflows/dependabot.yml

Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.

chore: dependabot.yml

---

.github/workflows/ci.yml
.github/workflows/mirror.yml
.github/workflows/release.yml

Nothing vulnerable, just tightening up permissions

ci: explicit permissions to actions

---

cli/src/main.rs

Bug fix
IPv6 addresses causes error
solves #546

fix(cli): ip address parsing to support both ipv4 and ipv6

---

Cargo.lock
crates/base/src/worker/pool.rs
crates/base/src/worker/worker_inner.rs
crates/base/src/worker/worker_surface_creation.rs
ext/workers/Cargo.toml
ext/workers/context.rs
ext/workers/lib.rs
ext/workers/user_workers.js
rust-toolchain.toml
types/global.d.ts

Feature
Introduce a new API in `EdgeRuntime.userWorkers` to track the memory state of user workers.

feat: add `EdgeRuntime.userWorkers.memStats`

---

crates/base/src/worker/pool.rs
crates/base/src/worker/worker_inner.rs

Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.

fix: clippy

---

Cargo.lock
ext/node/Cargo.toml
ext/node/ops/crypto/cipher.rs
ext/node/polyfills/internal/crypto/cipher.ts

Bug fix
Manually pulled from https://github.com/denoland/deno/pull/27818 and https://github.com/denoland/deno/pull/27476

fix(ext/node): some methods cause panic

---

Cargo.lock

Bug fix
In certain situations, memory leaks may occur due to `ModuleLoader`.

fix: memory leaks could occur due to `ModuleLoader`

---

ext/node/polyfills/zlib.ts

Bug fix
Manually pulled from https://github.com/denoland/deno/pull/27777

fix(ext/node): reference error in zlib.crc32

---

types/global.d.ts

Chore
Adds `otel` property to `UserWorkerCreateContext`

chore: update `types/global.d.ts`

---

ext/event_worker/events.rs
ext/event_worker/js_interceptors.rs
ext/runtime/js/bootstrap.js

fix(ext): handle log level correctly

---

crates/deno_facade/eszip/mod.rs

Bug fix
See https://github.com/supabase/edge-runtime/issues/597#issuecomment-3230875235 for more details.
Closes #597 
Closes FUNC-286

fix(deno_facade): don't randomly place contents when bundling

---

.github/workflows/stale.yml

Enhancement
It seems the issue cannot be closed due to insufficient permissions.
See https://github.com/actions/stale/issues/1131 and https://github.com/actions/stale/issues/1131#issuecomment-1959835001

chore(ci/stale): add an missing permission

---

cli/src/flags.rs
crates/deno_facade/eszip/mod.rs
crates/deno_facade/lib.rs

Bug fix
Fixes an issue where static files were not being extracted when running the unbundle command.

fix: static files weren't extracted when running the unbundle

---

crates/base/src/runtime/mod.rs

fix(inspector): debugger does not pause at the first statement when using the `--inspect-brk` flag
