README.md

Doc Update.
The README command was pointing to a non-existent file.
Considering the above command uses the full path, this one should too.
The command cannot be copied and pasted and run.
The command points to the correct file.
This command still doesn't work, actually. The parameters cannot
be expressed multiple times, and they don't override correctly. The
`run.sh` script is a little too basic to capture the nuance of what should
happen.
I (well, ChatGPT) wrote a more advanced version if you want, but it might be a little
too much:
```bash
#!/usr/bin/env bash
set -e
MAIN_SERVICE="./examples/main"
PORT=9000
cargo build
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
--main-service)
MAIN_SERVICE="$2"
shift # past argument
shift # past value
;;
-p|--port)
PORT="$2"
shift # past argument …
```

doc: Fix README script location

---

crates/sb_core/js/bootstrap.js
crates/sb_core/permissions.rs

This PR enables the use of Performance API (https://developer.mozilla.org/en-US/docs/Web/API/Performance). We disable the use high-res time to protect against timing attacks and fingerprinting (https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#security_requirements).

fix: enable performance API

---

Cargo.lock
crates/base/Cargo.toml
crates/base/src/edge_runtime.rs
crates/base/test_cases/oak/index.ts
crates/base/tests/integration_tests.rs
crates/sb_core/js/bootstrap.js
examples/file-upload/index.ts
examples/oak/index.ts
scripts/run.sh

This PR adds integration tests for user workers (oak server and file uploads). 
Along with the integration tests, I fixed couple of missing properties from the global scope - `DOMException` and `Deno.errors`.

Add integration tests for workers

---

crates/base/src/edge_runtime.rs

`console.log` was broken in main branch. It's fixed by setting the default stdio for `deno_io`.

fix: Use default stdio

---

crates/base/src/edge_runtime.rs
crates/base/src/worker_ctx.rs
crates/base/tests/main_worker_tests.rs

This PR handles user worker boot errors (eg: import map provided for worker is invalid). 
Handles part of scenarios that can cause #44 (there are some other scenarios not handled by this PR)

Handle worker boot errors

---

Cargo.lock
crates/base/Cargo.toml
crates/base/src/edge_runtime.rs
crates/base/src/worker_ctx.rs
crates/base/test_cases/main/index.ts
crates/sb_worker_context/essentials.rs
crates/sb_workers/lib.rs
crates/sb_workers/user_workers.js
examples/main/index.ts

Moved the logic to remove a worker from pool to worker_ctx, so it will
be done all instances. Previously, crashes would leave dead workers in
the pool.
This changes user workers to be reused by default, this can be overriden
by passing a `forceCreate` option when creating a worker.
Previously, main function had to maintain a cache of workers leading to
requests sent to already removed workers. This change would prevent
that.

Remove worker after completion

---

Dockerfile

Currently the docker builds fails because of missing rust bindgen dependencies. This PR addresses it.

fix: install LLVM deps in Dockerfile

---

crates/sb_workers/user_workers.js

If the response status is a null body status (101, 204, 205, and 304), do not try to stream the response body.

fix: correctly handle null body statuses

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/main.rs

Fixes a todo.
`edge-runtime --version` returns a hard-coded value.
`edge-runtime --version` returns the crate version that was set at compile time.
Note was `// TODO: set version on compile time`.

get version from cargo using clap

---

Cargo.lock
crates/base/Cargo.toml
crates/base/src/edge_runtime.rs
crates/base/test_cases/with_import_map/bar/index.ts
crates/base/test_cases/with_import_map/import_map.json
crates/base/test_cases/with_import_map/index.ts
crates/base/tests/import_map_tests.rs
examples/main/index.ts

This PR adds the option to provide an import_map_path to a user worker as a data URI.

feat: add support for providing import map as a data URI

---

crates/base/src/edge_runtime.rs
crates/base/src/worker_ctx.rs
crates/base/test_cases/invalid_imports/index.ts
crates/base/tests/worker_boot_tests.rs

Catch any module loading issues in boot phase by moving `load_main_module` to `worker::new`.

fix: move main module load to worker boot phase

---

crates/base/src/js_worker/module_loader.rs

Fixes #126 - Show a descriptive error message including the name of failed import.

fix: show more descriptive error when module not found

---

Cargo.lock
crates/base/Cargo.toml
crates/base/src/deno_runtime.rs
crates/base/src/server.rs
crates/base/src/utils.rs
crates/base/src/worker_ctx.rs
crates/base/tests/import_map_tests.rs
crates/base/tests/main_worker_tests.rs
crates/base/tests/null_body_status_null_body_tests.rs
crates/base/tests/oak_user_worker_tests.rs
crates/base/tests/tls_invalid_data_tests.rs
crates/base/tests/user_worker_tests.rs
crates/base/tests/worker_boot_tests.rs
crates/sb_worker_context/Cargo.toml
crates/sb_worker_context/essentials.rs
crates/sb_worker_context/events.rs
crates/sb_workers/event_worker.js
crates/sb_workers/events.rs
crates/sb_workers/lib.rs
examples/event-manager/index.ts

This adds a `metadata` field to the event object. Currently it's populated with `service_path` and `execution_id`.

Add metadata to events

---

crates/base/src/deno_runtime.rs
crates/sb_worker_context/events.rs
crates/sb_workers/lib.rs

Console events logged from user functions will also include the metadata.

fix: add metadata to console events

---

crates/base/src/deno_runtime.rs

Previously I had these errors logged under debug level, since they were propagated to the caller. But changing them to errors so it's easier to filter through logs.

fix: use error instead of debug for logging errors

---

crates/base/src/server.rs
crates/cli/src/logger.rs
crates/cli/src/main.rs
crates/module_fetcher/src/file_fetcher.rs
crates/module_fetcher/src/npm/resolution/graph.rs

If you run edge-runtime with `--log-source` option, it will emit log messages with the corresponding source file and line number.
eg:
```
crates/base/src/server.rs-164: client connection error (hyper::Error(IncompleteMessage))
```
This is quite useful for figuring out the source of some of the non-descriptive error messages.

Log source file

---

Dockerfile
README.md

Upgrade to bookworm base image to fix security vulnerabilities identified via ECR container scans.

feat: upgrade docker image to use bookworm base image

---

Dockerfile

There's a container vulnerability marked as high severity for the Perl module and edge-runtime doesn't rely on it.

fix: remove perl from runtime container

---

crates/sb_workers/user_workers.js
examples/main/index.ts

Fixes #149 #148 
Updated user workers to allow loading modules from any local path by default.

fix: allow loading modules from any local path

---

crates/base/src/js_worker/module_loader.rs

Treat unknown media types as JS

fix: parse unknown media type as JS

---

crates/sb_core/js/bootstrap.js

Correctly sets the `Window.prototype` on globalThis.

fix: globalThis.addEventListener

---

crates/base/test_cases/node-server/index.ts
crates/base/tests/test_node_server.rs
crates/node/polyfills/http.ts

This PR introduces the ability to use `createServer` imported from `node:http` in EdgeRuntime.
This functionality is currently not fully backwards compatible, things such as `AbortController` are missing support or listening events.
We probably want to create tickets for the things above.

Node create server

---

crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/server.rs
crates/base/tests/import_map_tests.rs
crates/base/tests/main_worker_tests.rs
crates/base/tests/null_body_status_null_body_tests.rs
crates/base/tests/oak_user_worker_tests.rs
crates/base/tests/test_node_server.rs
crates/base/tests/tls_invalid_data_tests.rs
crates/base/tests/user_worker_tests.rs
crates/base/tests/worker_boot_tests.rs
crates/sb_worker_context/essentials.rs
crates/sb_workers/lib.rs
crates/sb_workers/user_workers.js
examples/main/index.ts

Can provide module code as a string when creating a worker.
example,
```
const worker = createWorker({
....
maybeEntrypoint: "file:///src/index.ts",
maybeModuleCode: 'Deno.serve((req) => new Response("Hello from Module Code"));',
})
```

feat: support loading inline module code

---

crates/sb_core/js/denoOverrides.js

Adds `Deno.execPath()` function.

fix: add Deno.execPath()

---

crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/rt_worker/worker_pool.rs
crates/base/src/server.rs
crates/base/tests/import_map_tests.rs
crates/base/tests/main_worker_tests.rs
crates/base/tests/null_body_status_null_body_tests.rs
crates/base/tests/oak_user_worker_tests.rs
crates/base/tests/test_node_server.rs
crates/base/tests/tls_invalid_data_tests.rs
crates/base/tests/user_worker_tests.rs
crates/sb_worker_context/essentials.rs

Currently, the user worker creation blocks the worker pool events loops. This can cause deadlocks and make edge-runtime unresponsive. 
This PR modifies the user worker creation to be non-blocking.

fix: Made user worker create non-blocking

---

crates/event_worker/js_interceptors.rs
crates/sb_core/js/bootstrap.js

Excluding the v8 heap stats that were added by default to user worker logs. The op code is still there if we want to expose an explicity `console.memory` API.

fix: exclude default v8 heap stats from user worker logs

---

crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/utils.rs
crates/base/src/rt_worker/worker.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/rt_worker/worker_pool.rs
crates/sb_worker_context/essentials.rs
crates/sb_workers/lib.rs

Here's how it works:
- Every new worker gets a new UUID (this is reused for execution_id as well)
- There's a hash map of user_worker profiles (UUID is the key)
- Also, there's a 2nd hash map of `active_workers`  This maps `service_path` to  `key` (UUID)
- `UserWorkerMsgs::Retire` would remove the entry for worker from `active_workers`
-  `UserWorkerMsgs::Shutdown`  retires the worker first (if it's already not retired) and then removes it from `user_workers` hashmap.
-  `UserWorkerMsgs::Create` would return the UUID of `active_worker` if one already exists for `service_path` (`force create` argument bypasses this and re-creates the worker)
- `send_request` is called with UUID meaning retired workers can still receive messages from main (if it still holds a reference) or send responses to …

feat:  retire workers at the 50% of wall-clock limit

---

crates/base/src/commands.rs
crates/base/src/macros/test_macros.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/server.rs
crates/cli/src/main.rs
scripts/run.sh

Added two CLI options `--main-entrypoint` and `--events-entrypoint` to provide entrypoints when eszips are used for main and events workers.

fix: provide optional entrypoints for main/events eszips

---

crates/sb_core/js/http.js

Handle errors thrown inside handler functions in `Deno.serve`, so they don't break the event loop.

fix: handle errors in Deno.serve

---

crates/base/src/deno_runtime.rs

Deno 1.13 introduced `DENO_TLS_CA_STORE` environment variable that can be used to switch which certificate authorities Deno trusts for TLS: https://deno.com/blog/v1.13#use-system-certificate-store-for-tls
This PR bring this env variable support to edge-runtime by adapting the source code from deno: https://github.com/denoland/deno/blob/v1.37.0/cli/args/mod.rs#L467
`DENO_TLS_CA_STORE` allows 2 values: `mozilla` or `system`, and default to `mozilla`, which is the current default behavior as well. Users need to explicitly set it to `system` to trust the extra root cert stores.
It is not possible to make network request to services with self-signed certificate, even after adding the root-ca to the system with `ca-certificates`:
```dockerfile
FROM supabase/edge-runtime:latest
RUN apt update && …
```

Add support for DENO_TLS_CA_STORE env variable

---

crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/implementation/default_handler.rs
crates/base/src/rt_worker/utils.rs
crates/base/src/rt_worker/worker.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/event_worker/events.rs

This PR introduces a new `WorkerEvents::Shutdown` which includes the reason, cpu time, and memory used by the isolate as metadata. The separate  `CpuTimeLimit`, `WallClockTimeLimit`, `MemoryLimit` worker events are removed in favor of this. Event worker implementations need to update to use the `Shutdown` event instead of previous events.

feat: include isolate memory & cpu usage in shutdwon event

---

crates/base/src/rt_worker/worker_ctx.rs
crates/event_worker/events.rs
crates/sb_os/lib.rs

* removes unused memory usage op
* include total memory usage (heap + external) in shutdown event metadata

fix: include total memory usage in shutdown event

---

.github/workflows/release.yml

Looks like the last release build failed to create the docker images. Removing the step I added to see if it builds correctly.

fix: remove prepare build environment step

---

Dockerfile

Update the rust builder docker image to 1.73

fix: update rust docker builder to 1.73

---

crates/cli/src/main.rs

Show proper errors when invalid paths provided for the bundle command.

fix: handle invalid paths to bundle command

---

crates/base/src/commands.rs

Bug fix
This PR fixes the segfault when occurred the V8 tries to JIT compilation in running environments that supports PKU(Memory Protection Key; PKeys Userspace) feature.
It should only affect the environment that the PKU feature has enabled. You can check whether your environment supports the PKU feature using the below command:
```bash
lscpu | grep pku
Flags:                              ... xsaveopt arat pku ospke avx512_vnni...
```
Fixes #199 and might be
Resolves #200, resolves #204, resolves #207, resolves #226

fix: crash when V8 tries to JIT compilation in the PKU-supported environment

---

crates/base/src/commands.rs
crates/base/src/deno_runtime.rs

Bug fix, Refactor
After #227 the platform is initialized explicitly at the entry point. However, after initializing the platform, it was no longer able to set the v8 flags [\[1\]][1] [\[2\]][2] [\[3\]][3], so it is necessary to adjust the invocation order of the set v8 flag function to avoid v8's static assertion.
[1]: https://source.chromium.org/chromium/chromium/src/+/main:v8/src/flags/flags.cc;l=1074;drc=8e78783dc1f7007bad46d657c9f332614e240fd8;bpv=1;bpt=1
[2]: https://source.chromium.org/chromium/chromium/src/+/main:v8/src/flags/flags.cc;drc=8e78783dc1f7007bad46d657c9f332614e240fd8;l=912
[3]: https://source.chromium.org/chromium/chromium/src/+/main:v8/src/init/v8.cc;l=261;drc=8e78783dc1f7007bad46d657c9f332614e240fd8;bpv=1;bpt=1

refactor: set v8 flags before initialize v8 platform

---

Cargo.lock
crates/cli/.env.build
crates/cli/Cargo.toml
crates/cli/build.rs
crates/cli/src/main.rs

Feature
```
vscode ➜ /workspaces/edge-runtime $ ./target/debug/edge-runtime -V
edge-runtime 0.1.0
```
```
vscode ➜ /workspaces/edge-runtime (cli-deno-version) $ ./target/debug/edge-runtime -V
edge-runtime 0.1.0
deno 1.37.2 (debug, aarch64-unknown-linux-gnu)
```
Resolves #236

feat: printing out deno version in command line

---

crates/base/src/deno_runtime.rs
crates/node/ops/crypto/mod.rs

make clippy happy about `get_first` and `unnecessary_fallible_conversions` warnings
```
error: use of a fallible conversion when an infallible one could be used
--> crates/node/ops/crypto/mod.rs:413:65
|
413 |                     .verify_prehash(digest, &signature.to_vec().try_into()?)
|                                                                 ^^^^^^^^ help: use: `into`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_fallible_conversions
= note: `-D clippy::unnecessary-fallible-conversions` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::unnecessary_fallible_conversions)]`
```

chore: clippy

---

crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/rt.rs
crates/base/src/rt_worker/worker.rs

Fix
This change makes major(main, event) workers spawn in a separate pool, not the user worker pool.

fix: make major worker tasks managed separately from the user worker

---

crates/base/src/deno_runtime.rs

Bug fix
If exiting the V8 loop with an exception during script initialization, an isolate was explicitly detached from the thread by `scopeguard`.
It turns out an isolate calls the logic to detach itself from the thread when it is dropped by default, so the introduction of `scopeguard` was wrong.
This PR fixes `SIGSEGV` that triggered due to calling `v8::Isolate::Exit()` twice.

fix: `SIGSEGV` has triggered if initializing the main module was failed

---

crates/sb_core/js/http.js

Bug fix
https://discord.com/channels/839993398554656828/1201105204431556699
Reported-by: tazmaniax

fix(sb_core): adjusting http handler to be compatible with `oak@13.0.0`

---

crates/base/src/rt_worker/supervisor/mod.rs
crates/base/src/rt_worker/supervisor/strategy_per_request.rs
crates/base/src/rt_worker/supervisor/strategy_per_worker.rs

Bug fix
After #241 CPU time limit can be disabled by specifying zero. But In #244, I refactored the calculation for CPU time, as not consider the case where there might not be a CPU time limit.
This PR makes each supervisor policy consider the case that the CPU time limit is disabled.
Reported-by: @nicetomytyuk

fix: supervisor should also consider cases where the CPU time limit is zero

---

crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/implementation/default_handler.rs
crates/base/src/rt_worker/worker.rs
crates/base/src/rt_worker/worker_ctx.rs

Bug fix
Before: [link](https://github.com/supabase/edge-runtime/actions/runs/7717869794/job/21037912456#step:6:733)
After: [link](https://github.com/supabase/edge-runtime/actions/runs/7720419397/job/21045273639#step:6:121)
This PR synchronizes the drop timing of the unix stream sender with an isolate drop timing, which fixes the appearing error spams in particular tests after the [Deno core update PR](https://github.com/supabase/edge-runtime/pull/250).

fix: sync drop timing of unix stream sender to timing of an isolate drops

---

crates/sb_graph/lib.rs

Fix
Instead of letting the panic leak out by failing to strip a leading slash from the given module path, I add some assertions and make sure that things usually proceed instead of panicking when possible.
I don't know whether the problem is caused by the specifier being formatted to follow the Windows path format when ESZip is created in a Windows environment or caused by there being no slashes.
Because I currently don't have a Windows machine, so I take the most conservative approach possible to add logic to relax the leading slash restrictions.

fix(sb_graph): checking whether the path is relative and unix format while reading module path

---

.github/workflows/release.yml
crates/base/src/deno_runtime.rs
crates/cli/src/main.rs
crates/sb_core/js/bootstrap.js

Bug fix
```typescript
console.log(Deno.version);
// Output (Before / local build):
// {
//     "deno": "supabase-edge-runtime-0.1.0",
//     "v8": "11.6.189.12",
//     "typescript": "5.1.6"
// }
// Output (Before / prod):
// {
//     "deno": "supabase-edge-runtime-",
//     "v8": "11.6.189.12",
//     "typescript": "5.1.6"
// }
// Output (After / local build):
// {
//     "deno": "supabase-edge-runtime-0.1.0 (compatible with Deno v1.39.2)",
//     "v8": "11.6.189.12",
//     "typescript": "5.1.6"
// }
// Output (After / prod):
// {
//     "deno": "supabase-edge-runtime-[release version here] (compatible with Deno v1.39.2)",
//     "v8": "11.6.189.12",
//     "typescript": "5.1.6"
// }
console.log(DENO_VERSION);
// Output:
// 1.39.2
```
This PR indirectly relevant with the …

fix: show the actual deno cli version in `Deno.version`

---

crates/base/src/rt_worker/supervisor/strategy_per_request.rs
crates/base/src/rt_worker/supervisor/strategy_per_worker.rs
crates/base/src/rt_worker/worker.rs

Bug fix
There is no explicit lifetime synchronization path between the supervisor and isolate, so we cannot assume that `Isolate::request_interrupt` will always be scheduled.
The `IsolateInterruptData` passed as an argument has always been passed to `Box::into_raw`, so if the isolation is ever destroyed, the step of converting it back to a `Box<T>` to free the memory is omitted. We should have looked at the result of the `request_interrupt` call and freed the passed arguments in some cases, but we didn't, which led to a memory leak.

fix: thread safe handle may no longer have an isolate pointer

---

Cargo.lock
crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/worker.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/rt_worker/worker_pool.rs
crates/base/src/server.rs
crates/base/src/utils/integration_test_helper.rs
crates/base/tests/linux_pku_sigsegv_test.rs
crates/base/tests/main_worker_tests.rs
crates/sb_core/Cargo.toml
crates/sb_core/js/main_worker.js
crates/sb_core/lib.rs
crates/sb_workers/context.rs
examples/main/index.ts

Feature
This PR exposes an API to get runtime metrics.
> Note: This API is only exposed in the main worker.
> Note 2: The number of pending requests is the difference between the number of handled requests and the number of received requests, so I didn’t include it in the metric.
Usage
```typescript
serve(async () => {
...
if (pathname === '/_internal/metric') {
const metric = await EdgeRuntime.getRuntimeMetrics();
return Response.json(metric);
}
...
})
```
Sample output
```json
{
"mainWorkerHeapStats": {
"totalHeapSize": 11730944,
"totalHeapExecutable": 524288,
"totalPhysicalSize": 11165696,
"totalAvailableSize": 1508889368,
"totalGlobalHandlesSize": 16384,
"usedGlobalHandlesSize": 10144,
"usedHeapSize": 10273032,
"mallocedMemory": 278632,
"externalMemory": 79991,
"peakMallocedMemory": …
```

feat: runtime metric API

---

crates/base/src/deno_runtime.rs
crates/sb_core/js/bootstrap.js

Bug fix
Make edge-runtime conform to a known convention to make it more compatible with some services that check the prefix of the user agent.
Before
```typescript
console.log(navigator.userAgent);
// Output
// Supabase Edge Runtime
```
After
```typescript
console.log(navigator.userAgent);
// Output
// Deno/[deno version here] (variant; SupabaseEdgeRuntime/[release version here])
```
Before (Remote Server)
```json
{
...
"headers": {
"user-agent": "supabase-edge-runtime"
},
...
}
```
After (Remote Server)
```json
{
...
"headers": {
"user-agent": "Deno/[deno version here](variant; SupabaseEdgeRuntime/[release version here])"
},
...
}
```

fix: make the runtime user agent respect the convention

---

Dockerfile
scripts/install_onnx.sh

Fix the installation of onnx runtime in x86 platforms.

fix: installation of onnx runtime in x86 plaforms

---

crates/sb_core/js/bootstrap.js

Bug fix
Keep build info more concisely.
```typescript
console.log("Deno.build: ", Deno.build);
console.log("node.process.arch: ", process.arch);
console.log("Deno.version: ", Deno.version);
// ...
// Output
// Deno.build: {
//   target: "aarch64-unknown-linux-gnu",
//   arch: "aarch64",
//   os: "linux",
//   vendor: "unknown",
//   env: "gnu"
// }
// node.process.arch: arm64
// Deno.version: {
//   deno: "supabase-edge-runtime-0.1.0 (compatible with Deno v1.40.3)",
//   v8: "11.6.189.12",
//   typescript: "5.1.6"
// }
```
cc @laktek @andreespirela

fix: use `core.build` variable instead of maintain own `build` constant

---

crates/base/src/rt_worker/worker.rs

Bug fix
Align the value correctly to the time unit

fix: value must be aligned to the time unit being logged

---

Cargo.lock
crates/sb_ai/Cargo.toml
crates/sb_ai/ai.js
crates/sb_ai/lib.rs
crates/sb_core/js/bootstrap.js
examples/gte-small-ort/index.ts

Modified to initialize session once and reuse internal session/tokenizer.

fix: refactor Supabase AI API

---

Cargo.lock
crates/base/Cargo.toml
crates/base/build.rs
crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/server.rs
crates/base/src/utils.rs
crates/base/test_cases/websocket-upgrade/index.ts
crates/base/tests/integration_tests.rs
crates/http_utils/Cargo.toml
crates/http_utils/src/io/mod.rs
crates/http_utils/src/io/rewind.rs
crates/http_utils/src/io/upgraded2.rs
crates/http_utils/src/lib.rs
crates/http_utils/src/utils.rs
crates/sb_core/http.rs
crates/sb_core/http_start.rs
crates/sb_core/js/01_http.js
crates/sb_core/js/denoOverrides.js
crates/sb_core/js/http.js
crates/sb_core/js/main_worker.js
crates/sb_core/lib.rs
crates/sb_workers/Cargo.toml
crates/sb_workers/lib.rs
crates/sb_workers/user_workers.js
examples/main/index.ts
examples/oak-ws/index.ts
examples/ws/index.ts

Feature
This PR is to make it possible for the (user/main) worker to upgrade incoming requests to the WebSocket protocol.
* `EdgeRuntime.applyConnectionWatcher` is replaced by `EdgeRuntime.applySupabaseTag`
This change is a result of the need to track multiple pieces of data.

feat: WebSocket upgrade support

---

Cargo.lock
Cargo.toml
crates/base/Cargo.toml
crates/base/src/commands.rs
crates/base/src/deno_runtime.rs
crates/base/src/inspector_server.rs
crates/base/src/lib.rs
crates/base/src/macros/test_macros.rs
crates/base/src/rt_worker/implementation/default_handler.rs
crates/base/src/rt_worker/supervisor/mod.rs
crates/base/src/rt_worker/supervisor/strategy_per_request.rs
crates/base/src/rt_worker/supervisor/strategy_per_worker.rs
crates/base/src/rt_worker/worker.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/rt_worker/worker_pool.rs
crates/base/src/server.rs
crates/base/src/utils/integration_test_helper.rs
crates/base/tests/integration_tests.rs
crates/cli/src/main.rs
crates/cpu_timer/src/lib.rs
crates/sb_graph/lib.rs

Feature
As I said in supabase/cli#1822, using and debugging smoothly with EdgeRuntime in the local environment is quite difficult because we are providing a weak development environment.
I can't claim to solve those problems with this single PR, but I believe this will alleviate some of those difficulties.
* `--inspect [HOST_AND_PORT]` - Activate inspector on host:port (default: 127.0.0.1:9229)
* `--inspect-brk [HOST_AND_PORT]` - Activate inspector on host:port, wait for debugger to connect and break at the start of user script
* `--inspect-wait [HOST_AND_PORT]` - Activate inspector on host:port and wait for debugger to connect before running user code
* `--inspect-main` - This argument will only be used if you provide an argument that is one of the above. This argument allows the …

feat: allow creating an inspector session if using `oneshot` policy

---

Dockerfile

#292 broke the build due to a missing directory in docker build. This PR attempts to fix it.

fix: copy models dir from builder

---

crates/base/src/rt_worker/worker_pool.rs
crates/cpu_timer/src/lib.rs

Remove lint
Remove some rustc and clippy warning introduced in v1.77.0.
Note(static_mut_refs): https://github.com/rust-lang/rust/issues/114447

chore: rid some rustc and clippy lints introduced in v1.77.0

---

.devcontainer/Dockerfile

Chore
This is to ensure that the rust toolchain in the dev container is always tracking the latest version.
For more information on the toolchains and other packages tracked by the tag that will change due to the introduction of this PR, please see the link below:
https://github.com/devcontainers/images/blob/main/src/rust/history/dev.md

chore: adjust dev container base image as `dev-1-bookworm`

---

crates/base/src/commands.rs
crates/base/src/deno_runtime.rs
crates/base/src/lib.rs
crates/base/src/macros/test_macros.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/rt_worker/worker_pool.rs
crates/base/src/server.rs
crates/base/src/utils/integration_test_helper.rs
crates/base/test_cases/decorator_tc39/index.ts
crates/base/test_cases/decorator_typescript_with_metadata/index.ts
crates/base/test_cases/main_with_decorator/index.ts
crates/base/tests/integration_tests.rs
crates/cli/src/main.rs
crates/sb_graph/emitter.rs
crates/sb_graph/lib.rs
crates/sb_workers/context.rs
crates/sb_workers/lib.rs

Feature
* `--decorator` flag in subcommand `start` specifies the type of decorator to use on the main worker and event worker. If not specified, the decorator feature is disabled. (possible inputs: `tc39`, `typescript`, `typescript_with_metadata`)
* `--decorator` flag in subcommand `bundle` specifies the type of decorator to use when bundling. If not specified, the decorator feature is disabled. (possible inputs are same above)
Apart from the CLI arguments above, when you create a User Worker via the API in the main service, you can specify the type of decorator to use on the User Worker.
```rust
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DecoratorType {
/// Use TC39 Decorators Proposal - https://github.com/tc39/proposal-decorators …
```

feat: expose decorator options

---

Cargo.lock
Cargo.toml
crates/sb_core/Cargo.toml
crates/sb_core/util/checksum.rs

Performance optimisation
Currently the gen function performs atleast 33 separate string memory allocations which  can be avoided
Init a string with 64 bytes and push hashed bytes into that. This is only 1 allocation
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.

perf: optimise hash function to use single memory allocation

---

crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/implementation/default_handler.rs
crates/base/src/rt_worker/worker.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/server.rs
crates/cli/src/main.rs
crates/sb_core/http.rs
crates/sb_core/http_start.rs
crates/sb_core/net.rs
examples/chunked-text/index.ts

Refactor
This PR changes the stream type used to communicate between workers to `DuplexStream` instead of `UnixStream` to improve request throughput.
It was tested on a local machine, so it's imprecise, but it showed an improvement of about 10% in request throughput per second.
* `--tcp-nodelay` flag disables Nagle's algorithm. (Default is `true`)
Figure1. UnixStream, Debug
Figure2. DuplexStream, Debug
Figure3. UnixStream, Release
Figure4. DuplexStream, Release
Figure5. DuplexStream, Debug (examples/chunked-text, TCP_NODELAY OFF)
Figure6. DuplexStream, Debug (examples/chunked-text, TCP_NODELAY ON)

feat: use `DuplexStream` instead of `UnixStream` to communicate with workers

---

Cargo.lock
crates/base/src/macros/test_macros.rs
crates/base/src/server.rs
crates/base/test_cases/wasm/grow_standalone/index.ts
crates/base/tests/integration_tests.rs
crates/cli/src/main.rs
crates/sb_core/lib.rs
scripts/test_indefinitely.sh

Feature
This PR introduces a grace period to ensure that requests that were being processed when the runtime was about to be terminated by a `SIGTERM` or `SIGINT` unix signal can be processed reliably.
It is necessary for a reliable request-draining implementation in containerized software environments such as Docker, which uses the SIGTERM signal to terminate containers.
* `--graceful-exit-timeout` flag allows the user to specify the maximum amount of grace the runtime can wait, **in seconds**, with a default value of `15`.
> Note that this flag is introduced because arbitrary requests cannot wait indefinitely.
* (Experimental) `--experimental-graceful-exit-keepalive-deadline-ratio` flag specifies maximum period of time that incoming requests can be processed over a pre-established …

feat: support graceful shutdown by unix signals

---

crates/sb_ai/ai.js

Changes `sb_ai` to fallback to ollama for all models that are not locally available (ie. except for `gte-small`).

fix: fallback to ollama if model is not locally available

---

DEVELOPERS.md

Drive-by PR. Had to follow the `DEVELOPERS.md` to setup edge-runtime into a container and realized that the [run script defaults to port 9998 rather than 9000](https://github.com/supabase/edge-runtime/blob/main/scripts/run.sh#L3)
We can also change the run script if that's better.

docs: change default port in DEVELOPERS.md

---

DEVELOPERS.md

Another drive-by docs PR to add the option to use Orbstack as a development environment for MacOS users wishing to do development related AI models

docs: add option to use Orbstack

---

crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/implementation/default_handler.rs
crates/base/src/rt_worker/supervisor/strategy_per_request.rs
crates/base/src/rt_worker/supervisor/strategy_per_worker.rs
crates/base/src/rt_worker/worker.rs
crates/event_worker/events.rs

Bug fix
```typescript
// Inputs below will disable the wall clock limit.
const workerTimeoutMs = -999;
const workerTimeoutMs = -1;
const workerTimeoutMs = 0;
const worker = EdgeRuntime.userWorkers.create({
...,
workerTimeoutMs
});
```
```typescript
// Worker is created and immediately terminated by the wall clock limit. However, if the script
// is lightweight enough to initialize quickly, the request can be processed before the worker exits.
const workerTimeoutMs = 1;
const worker = EdgeRuntime.userWorkers.create({
...,
workerTimeoutMs
});
```
```typescript
// main.ts
const workerTimeoutMs = 2000;
const worker = EdgeRuntime.userWorkers.create({
...,
workerTimeoutMs
});
// serve.ts
async function sleep(ms: number) {
return new Promise(res => {
setTimeout(() => {
res(void 0);
}, ms)
});
} …
```

fix: make the wall clock limit handle some edge cases correctly

---

crates/base/test_cases/oak-v12-file-upload/index.ts
crates/base/test_cases/oak-with-jsr/index.ts
crates/base/test_cases/oak/index.ts
crates/base/tests/integration_tests.rs
crates/sb_module_loader/standalone/standalone_module_loader.rs
examples/oak-with-jsr/index.ts

Bug fix
Now that Deno has deployed the `jsr:` specifier [globally](https://jsr.io), the edge runtime should also support it.
Previously, this specifier was not properly supported, causing the module resolution phase to be an indefinite pending state.
Fixes #335

feat: correctly handle import statement with JSR specifier

---

crates/sb_core/js/main_worker.js
crates/sb_os/lib.rs
examples/main/index.ts

Adding it to the `EdgeRuntime` namespace instead of the `Deno` namespace to prevent accidentally exposing it in user workers. Also, we are implementing a customized version of it for performance reasons (ie. only support in Linux via sysinfo)

feat: expose systemMemoryInfo API for main worker

---

Cargo.lock
Cargo.toml
crates/base/Cargo.toml
crates/base/src/lib.rs
crates/base/src/macros/test_macros.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/server.rs
crates/base/src/timeout.rs
crates/base/tests/integration_tests.rs
crates/cli/Cargo.toml
crates/cli/src/flags.rs
crates/cli/src/main.rs
crates/cpu_timer/src/lib.rs
crates/node/errors.rs
crates/npm/managed/mod.rs
crates/npm/managed/tarball.rs
crates/sb_core/cache/fetch_cacher.rs
crates/sb_fs/virtual_fs.rs
crates/sb_graph/graph_resolver.rs

Feature
This PR allows setting a timeout between when the connection is established and when the runtime fully consumes the request body, making it less vulnerable to attacks such as Slowloris.
* `--request-read-timeout` flag specifies maximum time in milliseconds that can be waited from when the connection is accepted until the request body is fully read. (disabled by default)

feat: support read timeout for inbound HTTP requests

---

crates/sb_graph/emitter.rs

Enhancement
This PR improves EmitterFactory so that it can determine `no npm` mode via the `allowRemoteModules` passed in by the user. (The original option for this is `no_npm`, but this is not exposed in js land).
```typescript
// main service
await EdgeRuntime.userWorkers.create({
servicePath,
memoryLimitMb,
workerTimeoutMs,
noModuleCache,
allowRemoteModules: false,
...
});
// some user script
import * as jose from 'npm:jose'
...
```
Output
```
...
DEBUG Snapshot already up to date. Skipping pending resolution.
failed to load 'npm:jose': npm specifiers were requested; but --no-npm is specified
An error has occured
InvalidWorkerCreation: worker boot error failed to load 'npm:jose': npm specifiers were requested; but --no-npm is specified
at async UserWorker.create …
```

fix: make `EmitterFactory` respect `allow_remote_modules` option when determining `no npm` mode

---

crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/rt_worker/worker_pool.rs
crates/base/src/server.rs
crates/base/src/timeout.rs
crates/base/src/utils/integration_test_helper.rs
crates/base/test_cases/chunked-char-first-6000ms/index.ts
crates/base/test_cases/chunked-char-variable-delay-max-6000ms/index.ts
crates/base/test_cases/sleep-5000ms/index.ts
crates/base/test_cases/websocket-upgrade-no-send-node/index.ts
crates/base/test_cases/websocket-upgrade-no-send/index.ts
crates/base/tests/integration_tests.rs
crates/cli/src/flags.rs
crates/cli/src/main.rs
crates/http_utils/src/utils.rs

Feature
> Note: This PR is behind [PR-337](https://github.com/supabase/edge-runtime/pull/337). (PR will be rebased after PR-337 has been merged into main)
This PR introduces the feature for a user worker to force a response to complete (timeout) if it does not complete the response within a specified amount of time after receiving the request from the pooler.
* `--request-idle-timeout` flag specifies maximum time in milliseconds that can be waited from when a worker takes over the request. (disabled by default)
|Response Type|Behavior|
|---------------|---------|
|`Content-Length` present (ie. not stream response)|Respond with [HTTP 408 Request Timeout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408)|
|No `Content-Length` present (ie. stream response)|Emit an EOF to a stream …

feat: support idle timeout for HTTP requests 

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
Cargo.lock
crates/sb_ai/Cargo.toml
crates/sb_ai/lib.rs
examples/k6-gte/index.ts
k6/specs/gte.ts

Bug fix
No description
> Note: Intermittent segfault seems to only occur when the `EDGE_RUNTIME_WORKER_POOL_SIZE` env var is greater than 1. (In debug build, this value was 1 by default.)

fix(sb_ai): intermittent segfault when creating a `Ort::Session`

---

crates/base/src/rt_worker/worker_ctx.rs
crates/base/tests/integration_tests.rs

Enhancement
By default, idle timeout is for connections that have been successfully established, so a 504 status code should be emitted instead of a 408 status code.
cc @laktek

fix: change the status code emitted when an idle timeout occurs for a worker

---

crates/cli/src/main.rs

Improvement
The PR relaxes the restriction that inspector feature could only be activated in `oneshot` policy.
> Caveats: This relaxation allows policies other than `oneshot` to create inspector sessions, so the worker will remain until the `wallclock limit` or `cputime limit` is reached. This means that source changes by users will not result in immediate feedback to the worker.

fix: relaxing the condition which can be activated inspector feature

---

crates/base/src/rt_worker/worker.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/rt_worker/worker_pool.rs
crates/base/src/server.rs
crates/base/src/utils/integration_test_helper.rs
crates/base/test_cases/array-alloc-sync/index.ts
crates/base/test_cases/array-alloc/index.ts
crates/base/test_cases/boot_err_user_worker/index.ts
crates/base/tests/integration_tests.rs
crates/event_worker/events.rs
crates/sb_workers/context.rs
crates/sb_workers/lib.rs
examples/event-manager/index.ts

Enhancement
This PR makes to record `InvalidWorkerResponse` with an event loop error message in the response instead of emitting `RequestCancelledBySupervisor` if an uncaught error is encountered by the user script.
> Note: Error message recorded in the response may be something other than an event loop error message due to race conditions caused by a worker exiting quickly. (but error kind is still fixed to `InvalidWorkerResponse`)
Example
```typescript
// Throw an exception from the top level (will cause an event loop error and a worker will be terminated immediately)
throw new Error("meow");
// Deno.serve((_req) => new Response("meow"));
```
Response (Before this PR)
```jsonc
// 500 Internal Server Error
{
"msg": "WorkerRequestCancelled: request has been cancelled by supervisor"
}
``` …

fix: don't emit `RequestCancelledBySupervisor` when event loop error has been raised

---

Cargo.lock
Cargo.toml
crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/supervisor/mod.rs
crates/base/src/rt_worker/supervisor/strategy_per_request.rs
crates/base/src/rt_worker/supervisor/strategy_per_worker.rs
crates/base/src/rt_worker/worker.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/event_worker/Cargo.toml
crates/event_worker/events.rs

Enhancement
Clarify which memory limit kind caused termination to be requested and expose the memory metrics used to decide to terminate into the event record.
Sample (MemCheck / MemCheckState::check)
```
2024-06-04T03:20:14.726849Z DEBUG sb-supervisor base::rt_worker::worker_ctx: memory limit triggered: isolate: 6745b2ae-075e-4a5d-8414-912411de8aaf, detail: MemoryLimitDetailMemCheck { captured: 158894854 }    
2024-06-04T03:20:14.728807Z ERROR sb-supervisor base::rt_worker::supervisor::strategy_per_worker: memory limit reached for the worker: isolate: 6745b2ae-075e-4a5d-8414-912411de8aaf    
2024-06-04T03:20:14.731119Z ERROR          main base::rt_worker::worker_pool: failed to send request to user worker: request has been cancelled by supervisor    
2024-06-04T03:20:14.829827Z TRACE …
```

fix: include detailed memory metric in event record

---

Cargo.lock
crates/base/src/deno_runtime.rs
crates/sb_module_loader/Cargo.toml
crates/sb_module_loader/standalone/mod.rs
crates/sb_module_loader/standalone/standalone_module_loader.rs

Bug fix
For non-entrypoint scripts, source maps is not loaded by default because it is stored separately in eszip.
This PR will make the source map automatically append to the end of the module code when it is loaded by the module loader if it exists in eszip. (However, due to the extra cost of copying a source buffer, it is only performed if the inspector is enabled)

fix: attaching inline source map into module code when inspect is enabled

---

Dockerfile

Bump rust builder image to `1.78-bookworm`

fix: bump rust builder image to `1.78-bookworm`

---

Dockerfile

Bug fix
Downgrade the rust builder image due to an upstream issue.
Note: denoland/deno#23778

fix: downgrade rust builder image to `rust:1.77.2-bookworm`

---

Cargo.lock
Cargo.toml
crates/base/Cargo.toml
crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/worker.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base_mem_check/Cargo.toml
crates/base_mem_check/src/lib.rs
crates/event_worker/Cargo.toml
crates/event_worker/events.rs
crates/event_worker/lib.rs
crates/sb_core/Cargo.toml
crates/sb_core/lib.rs
examples/event-manager/index.ts

Enhancement
This PR changes the original v8 memory statistics that were the basis of the memory limitation to be exposed, rather than the arbitrarily calculated memory usage by `MemCheck` (Previously `MemCheckState`).
```
{
timestamp: "2024-06-14T00:35:08.578Z",
event_type: "Shutdown",
event: [Object: null prototype] {
reason: [Object: null prototype] {
Memory: [Object: null prototype] { limited_by: "mem_check" }
},
cpu_time_used: 74,
memory_used: [Object: null prototype] {
total: 67685841,
heap: 6460736,
external: 61225105,
mem_check_captured: [Object: null prototype] {
current: [Object: null prototype] {
totalHeapSize: 8626176,
totalHeapSizeExecutable: 262144,
totalPhysicalSize: 7131136,
totalAvailableSize: 61063776,
totalGlobalHandlesSize: 24576,
usedGlobalHandlesSize: 18976, …
```

fix: include more detailed memory metric in mem check record

---

crates/base/src/deno_runtime.rs

Enhancement
To get accurate memory stats, this PR makes changes `MemCheck` stops updating memory stats when the memory limit is reached.

fix: don’t update mem stat if exceeded the memory limit

---

crates/node/polyfills/http.ts

Bug fix
h2 protocol was unintentionally enabled in the context of npm modules due to the rid of the HttpClient not being passed properly. This PR fixes that.
Fixes #369

fix(node): refer the internal rid correctly

---

Cargo.lock
Cargo.toml
crates/cli/src/main.rs
crates/sb_module_loader/Cargo.toml
crates/sb_module_loader/standalone/standalone_module_loader.rs

Enhancement
Introduces `tracing` crate to improve the edge runtime debugging experience.
In this PR, I'm not trying to apply tracing to all of the codebase, just the `sb_module_loader` crate. (There's nothing special about this 😅)
* **cli**: Changed the behavior of the `-v` `--verbose` cli flag in `cli/tracing` feature flag
When this feature flag is enabled and `-v` or `--verbose` flag is set, detailed tracing span events are output to the console.
With `-v` or `--verbose` flag
```bash
...
2024-06-24T03:07:11.447652Z DEBUG ThreadId(04) load{specifier="https://deno.land/std/http/status.ts"}: sb_module_loader::standalone::standalone_module_loader: new
2024-06-24T03:07:11.447670Z DEBUG ThreadId(04) load{specifier="https://deno.land/std/http/status.ts"}: …
```

chore: introduce `tracing`

---

crates/base/tests/integration_tests.rs
crates/sb_workers/user_workers.js

Bug fix
For a promise to a WritableStream that streams the body of an inbound request to a user worker, the promise might be rejected in some cases.
Previously, if this promise was rejected, an exception to this rejection would be propagated to the caller.
```typescript
let [sent, res] = await Promise.allSettled([reqBodyPromise, resPromise]);
```
> The promise `res`, which gets the response from the user worker, and the promise `sent`, which streams the request body to the user worker, are bound by `Promise.allSettled`, so it will not return until all of the passed Promises have performed their actions.
However, propagating exceptions for these `sent` is turns out to be undesirable. 
This is because the user worker may consume the request object abnormally, or `op_user_worker_fetch_send` …

fix(sb_workers): don't propagate promise rejection on request body streaming failure

---

Cargo.lock
crates/node/Cargo.toml

Bug fix
remove unused dependency `deno_permissions` in sb_node crate.

chore: remove unused dependency `deno_permissions`

---

Cargo.lock
Cargo.toml
crates/base/Cargo.toml
crates/base/src/deno_runtime.rs
crates/base/src/lib.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/tracing.rs
crates/base_mem_check/src/lib.rs
crates/cli/Cargo.toml
crates/cli/src/env.rs

Bug fix, Enhancement
* Makes `malloced_memory` calculation optional (`EDGE_RUNTIME_INCLUDE_MALLOCED_MEMORY_ON_MEMCHECK` env var can be used to restore the old behavior).
* Simplifies memory limit callback trigger logic.
* Fixes a mistake made in a previous `MemCheck` related PR.
* Enables `tracing_subscriber` in the test build (ie. `#[cfg(test)]`)

fix: revisit `MemCheck` related logics

---

crates/base/test_cases/serve-declarative-style/index.ts
crates/base/tests/integration_tests.rs
crates/sb_core/js/00_serve.js
crates/sb_core/js/bootstrap.js
crates/sb_core/lib.rs
examples/serve-declarative-style/index.ts

Feature
This PR allows declarative-style fetch handlers like the one below.
```typescript
export default {
async fetch(_req) {
return new Response("Hello world!");
},
}
```
https://docs.deno.com/runtime/manual/tools/serve/

feat: support declarative style fetch handler

---

Cargo.lock
Cargo.toml
crates/base/src/deno_runtime.rs

Bug fix
It seems that the path to calling `thread::unpark` was enabled when eszip content became possible to load asynchronously.
The current inspector implementation upstream doesn't like it when `park` is called at a certain stage of `poll_session` and then immediately unparked. This results in reaching `unreachable!`, which causes panic.
* https://github.com/supabase/cli/issues/2646
* https://github.com/supabase/deno_core/commit/d73dc1e1845d00cc2e8d2a32caf5859cc300386b
Reported-by: @daniel-sc

fix: inspector causes panic

---

crates/base/src/rt_worker/worker_ctx.rs
crates/base/tests/integration_tests.rs
crates/sb_graph/eszip_migrate.rs
crates/sb_graph/graph_util.rs
crates/sb_graph/lib.rs
crates/sb_module_loader/standalone/mod.rs

Bug fix, Enhancement
* **sb_graph**: Don't propagate unnecessary panic
* **base**: Give the runtime an explicit chance to handle an interruption request by the supervisor (Please see the commit description for the detail)

fix: improve stability

---

crates/node/ops/crypto/cipher.rs
crates/node/ops/crypto/mod.rs
crates/node/ops/http2.rs
crates/node/polyfills/internal/crypto/cipher.ts

fix(node): mitigate denoland/deno#25279

---

Cargo.toml
Dockerfile

Enhancement
Added debug symbols to the release profile to make core dump analysis easier.

chore(build): add debug symbols to release profile

---

Cargo.toml

Chore
This PR adjusts the release profile.
* For lto, I've changed from fat to thin.
* The main reason for changing this is that FullLTO (Traditional LTO) only works on a single thread and consumes a very large amount of memory. Previously we were seeing a moderate impact on build times with this option enabled because we didn't enable debug symbols in our release profile, but now I am seeing unacceptable build times and memory consumption.
* No performance change was detected on the local machine due to this change.
* Increase the debug symbol level to maximum.
* In Dockerfile, the debug symbol is separated into a file by the objcopy, so no significant size increase was found for the edge runtime binary itself.
* The size of the debug symbol is almost 2x(63M -> 114M) and the size of edge …

chore(build): adjust release profile

---

crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/worker.rs

Bug fix
This is a fix for another point that may have caused the segfault.

fix(base): thread-local state of `v8::Isolate` can be corrupted while initializing DenoRuntime in `Worker::start`

---

Cargo.lock
crates/base/src/rt_worker/implementation/default_handler.rs
crates/base/src/rt_worker/worker.rs
crates/base/src/rt_worker/worker_ctx.rs
crates/base/src/rt_worker/worker_pool.rs
crates/base/test_cases/graph-error-1/index.ts
crates/base/test_cases/graph-error-2/index.ts
crates/base/tests/integration_tests.rs
crates/base_rt/Cargo.toml
crates/base_rt/src/error.rs
crates/base_rt/src/lib.rs
crates/sb_workers/lib.rs

fix: render detailed error message for failed to create a graph

---

.devcontainer/devcontainer.json

Chore
Removes an unused feature from devcontainer.json.
In particular, this feature had a problem with changing the ownership of subdirectories under /usr/local/cargo during enable, so rust-analyzer and cargo would not work properly without typing `chown -R vscode:vscode /usr/local/cargo` command manually.

chore(devcontainer): remove `cargo-make` feature

---

crates/sb_graph/lib.rs

Bug fix
Fixes an issue where reading sources from the eszip binary causes an unexpected EOF due to reading the checksum size assuming as a constant (32 bytes).

fix(sb_graph): checksum size is not a constant

---

crates/sb_ai/js/ai.js
crates/sb_ai/lib.rs

Bug fix
Slack: https://supabase.slack.com/archives/C02KMRX22NR/p1731011614966199

fix(sb_ai): make sure the shared session is initialized before running inferences

---

crates/base/src/deno_runtime.rs
crates/base/src/utils/json.rs
crates/base/src/utils/mod.rs
crates/sb_core/js/bootstrap.js
crates/sb_workers/context.rs
crates/sb_workers/lib.rs

Enhancement
The purpose of this is to allow bootstrapping to be more granular, by allowing extra context to be passed in from js land.
We've observed instances of using the Deno.readFileSync API in prod, but because bootstrap.js is hardcoded to block these APIs, it was difficult to react quickly to unblock them.
```typescript
await EdgeRuntime.userWorkers.create({
..
context: {
useReadSyncFileAPI: true
}
});
```

fix(sb_workers): allow extra context to be passed in from js land

---

crates/sb_ai/onnxruntime/mod.rs
crates/sb_ai/onnxruntime/session.rs
examples/k6-ort-rust-backend/index.ts
examples/main/index.ts
k6/specs/ort-rust-backend.ts

Bug fix
The `cleanup` method can't verify if sessions created via `op_sb_ai_ort_init_session()` are still in use.
This PR fixes this issue, by ensure that sessions created from `op_sb_ai_ort_init_session()` will have its reference stored in Worker's `OpState`. This guarantees that `cleanup` method will don't drop `Sessions` attached to an active worker.
Also was introduced a better error handling when it can't found a session.
**Solved:**
> *Trying to retrieve a session that was dropped while the worker was still consuming it*

fix(sb_ai): Sessions are dropped while still in use

---

.github/workflows/ci.yml

Chore
(cherry picked from commit 5ef1122703466517b4fc88e73cea1773bc5122ff)
in case opening a PR using a branch: https://github.com/supabase/edge-runtime/actions/runs/11982000952/job/33409254971
in case opening a PR using a branch of the fork repository: https://github.com/supabase/edge-runtime/actions/runs/11981885370/job/33408929366

chore(ci): s3 cred install step didn't gate correctly

---

Cargo.lock
crates/sb_fs/Cargo.toml
crates/sb_fs/fs/s3_fs.rs

Bug fix
According to dependabot, <= `webpki@0.22.1` is vulnerable to CPU denial of service attacks.
However, this version is only used for debugging and development purposes by hyper-proxy, so it can be tolerated.
Ultimately, this is a problem because aws-rust-sdk does not currently provide an appropriate hyper v1 connector, and if the issue is resolved (which does not seem likely to be resolved in the short term), the vulnerability can be completely resolved by upgrading the connector version.
The proxy feature is used very limitedly, so I am adding a feature gate to make it available only through the cargo feature to clarify its meaning.
```
│   ├── hyper-proxy v0.9.1
│   │   ├── bytes v1.6.1
│   │   ├── futures v0.3.30 (*)
│   │   ├── headers v0.3.9 (*)
│   │   ├── http v0.2.11 (*)
│ …
```

fix(sb_fs): make s3 fs proxy capability to unsafe feature

---

crates/base/src/rt_worker/supervisor/mod.rs
crates/base/src/rt_worker/supervisor/strategy_per_request.rs
crates/base/src/rt_worker/supervisor/strategy_per_worker.rs

Enhancement
When the worker is retired early by the supervisor, provide timing to run GC forcibly.

perf(base): sent low memory notification when worker switches to retired state

---

crates/base/src/deno_runtime.rs
crates/base/test_cases/mark-background-task/index.ts
crates/sb_core/js/async_hook.js
crates/sb_core/js/bootstrap.js
crates/sb_core/js/main_worker.js
examples/mark-background-task/index.ts
types/global.d.ts

Refactor, Enhancement
* Move `markAsBackground` to `EdgeRuntime.waitUntil`
* Fill global definitions in `global.d.ts` as far as possible (We haven't had proper type definitions until now, so now is the time.)

fix: move `markAsBackground` to `EdgeRuntime.waitUntil`

---

crates/base/src/deno_runtime.rs
crates/sb_ai/js/onnxruntime/cache_adapter.js
crates/sb_core/js/bootstrap.js

Miscellaneous
November cleanup.
FYI @kallebysantos , you can access the debug variable through the `internals`.
```typescript
import { internals } from 'ext:core/mod.js';
// in debug build
console.log(internals.bootstrapArgs.opts.debug); // true
```
* Now, `DenoRuntime` invokes the `globalThis.bootstrapSBEdge` function directly instead of invoking it through `execute_script`.
* All the arguments passed to `globalThis.bootstrapSBEdge` are objectified. They are no longer arrays, which will allow for more flexibility when we are adding flags in the future.
* Fixes an issue where annoying error messages were emitted due to an exception propagated by `cache_adaptor.js` when `transformers.js` accessed the Cache API.

fix: polishing the worker bootstrap phase and ridding annoying cache adaptor errors emitted from `transformers.js`

---

crates/base/src/deno_runtime.rs
crates/base/src/rt_worker/supervisor/mod.rs
crates/base/src/rt_worker/supervisor/strategy_per_worker.rs
crates/base/test_cases/main/index.ts

Bug fix
This PR fixes the issue where the `beforeunload` event is not triggered in the early drop state.

fix: `beforeunload` event didn't trigger on the early drop state

---

crates/base/src/deno_runtime.rs

Bug fix
`DenoRuntime::new` may return an error, so `JsRuntime` should not be wrapped with `ManuallyDrop` early. This causes memory leaks.

fix(base): don't wrap `JsRuntime` with `ManuallyDrop` early

---

crates/sb_fs/build.rs

Bug fix
It just appends the `cargo::return-if-changed` instruction to the build script. 
Because it could not detect changes `.env` before.

fix(sb_fs): update `build.rs`

---

crates/sb_fs/tests/integration_tests.rs

Chore
Since the s3 credential is shared across each Github Action, the test could have failed if the test was running on multiple actions.
This PR solves this problem by placing a random string at the beginning of the path referenced by each test.

chore(fs): allow running integration tests in parallel

---

.github/workflows/ci.yml
crates/base/src/deno_runtime.rs
crates/base/src/worker/pool.rs
crates/base/src/worker/supervisor/strategy_per_worker.rs
crates/base/test_cases/early-drop-mem/index.ts
crates/base/test_cases/early-drop-wall-clock/index.ts
crates/base/tests/integration_tests.rs
types/global.d.ts

Feature, Enhancement
This PR makes the early drop be performed even under other resource limits.
* wallclock limit
* It may be triggered when half of its limit specified by the main worker has elapsed.
* worker memory limit
* It may be triggered when half of its limit specified by the main worker has been reached.
Nevertheless, the fact that if there are remaining requests or background tasks, the runtime will not trigger the early drop is unchanged.
~Blocked-by: #462~

feat(base): make able to trigger early drop with other resources

---

Cargo.lock
cli/Cargo.toml
ext/event_worker/Cargo.toml
ext/event_worker/js_interceptors.rs

Bug fix
`CliLogger` does not trace the log entries emitted by tracing, so if the user does not explicitly set the event worker, the edge runtime does not render these logs to stdout or stderr.

fix(ext/event_worker): don't use `tracing` as the log backend if `cli/tracing` feature flag is not enabled

---

crates/base/src/worker/pool.rs
deno.json
examples/main/index.ts
examples/serve-html/bar.html
examples/serve-html/foo.html
examples/serve-html/index.ts
ext/workers/lib.rs

Currently, static file patterns (ie. static files that can be added to the eszip bundles) can be specified only via CLI flag `--static`. This PR modifies create options for user worker to support providing static patterns.

fix: allow setting static patterns when creating a user worker

---

Cargo.lock
Cargo.toml
ext/ai/Cargo.toml
ext/ai/onnxruntime/tensor.rs
ext/ai/utilities/Cargo.toml
ext/ai/utilities/lib.rs

Bug fix, CRITICAL
If a `Tensor` received from JS land haves `data.length` not compatible with the `dims`  then when feeding the `Session` a **Segmentation Fault: 11** error will be panic!.
The tensors is successfully handled by `rust` as well `JsTensor::extract_ort_input` but error will be panic when feed this values into the `Session`.
```js
const t1 = new Tensor("float32", [], [1] ); // This one always will result in panic!
const t2 = new Tensor("float32", [0.1, 0.2, 0.3], [1, 2] ); // Session may safely throws while validating inputs
// ...
await core.ops.op_sb_ai_ort_run_session("123", { t1, t2 });
```
```bash
./scripts/run.sh: line 13: 12963 Segmentation fault: 11  RUST_BACKTRACE=full ./target/debug/edge-runtime "$@" start --main-service ./examples/main --event-worker …
```

fix(ext/ai): Invalid tensor length causing Segmentation Fault

---

.devcontainer/Dockerfile
Dockerfile

Bug fix
`libopenblas` was introduced on #486 but was not added to container deps.
<details>
<summary>error log</summary>
```bash
$ ./scripts/run_dind.sh
edge-runtime: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
```
</details>
Install `libopenblas` to Devcontainer as well the Docker image.
---
*Question: Do we really need this `blas` lib?*

fix: missing `libopenblas.so.0` 

---

crates/graph/graph_util.rs

Bug fix
Fixes parsing strings after `#` as fragments when converting PathBuf containing the `#` character to Url.
Closes #489

fix(graph): convert file path with special characters to url correctly

---

crates/base/src/deno_runtime.rs
crates/base/test_cases/use-tmp-fs-3/index.ts
crates/base/test_cases/user-worker-san-check/.blocklisted
crates/base/tests/integration_tests.rs
crates/fs/impl/tmp_fs.rs
ext/core/js/bootstrap.js

Bug fix
Remove realPathSync from the blocklist.
Deno.realPath(Sync) returns a path on the actual filesystem (e.g. /tmp/.tmpe8EebZ/meow), so we need to add extra steps to ensure that prefixfs can route these paths to tmpfs.
closes FUNC-191

fix: unblock `Deno.realPathSync`

---

.github/workflows/ci.yml

Chore
dependabot does not have access to the secrets in the repository.

chore: skip s3 cred install step if the action is triggered by dependabot

---

DEVELOPERS.md

Update the docs to mention increasing the docker container max memory.
If the max memory is not increased while trying to run tests in the dev container, there will be errors during the build process.
The tests run and pass properly.
N/A

docs: recommend increasing Dev Container memory allocation

---

DEVELOPERS.md

Update docs
Developer instructions for updating deno do not mention updating ext/node.
Developer instructions for updating deno do mention updating ext/node.
Discovered that ext/node needs to be updated while working on https://github.com/supabase/edge-runtime/pull/488

docs: Add blurb to docs about updating ext/node when updating Deno version

---

.github/workflows/release.yml
.releaserc

Chore
Now we have `develop` branch.
Any release that is published from this branch should be marked as `Pre-release`.

fix: update github release workflow

---

crates/base/test_cases/byonm-typescript/meow.ts
crates/base/test_cases/byonm-typescript/package.json
crates/base/tests/integration_tests.rs

Chore
This PR adds an integration test that loads typescript with byonm feature.
Note that the `npm:` prefix is not added in an import statement for `is-odd` package in meow.ts:
https://github.com/supabase/edge-runtime/blob/5bd4e8c2a2fa7f399664ff8abb45a5ce72659c31/crates/base/test_cases/byonm-typescript/meow.ts#L1-L2

chore: add an integration test for byonm feature

---

deno/graph_util.rs

Bug fix
edge runtime does not allow specifying Deno flags, so it is recommended not to make such an error message to avoid confusion for users.
Ref: https://supabase.slack.com/archives/C02KMRX22NR/p1740553071388899?thread_ts=1740552521.862859&cid=C02KMRX22NR

fix: do not mention about unstable sloppy import flag

---

Cargo.lock

Bug fix
The dependabot was bumped up the hickory-proto to `0.25.0-alpha.5` earlier, but Deno's resolveDns was broken due to the enhanced DNSSEC validation in that version.
Upstream is still at `0.25.0-alpha.4` and does not seem to be resolved, so we need to lower the version to make resolveDns work properly again.
Ref: https://github.com/supabase/edge-runtime/security/dependabot/52
Ref: https://github.com/hickory-dns/hickory-dns/pull/2560
Ref: https://github.com/hickory-dns/hickory-dns/pull/2560/files#diff-3dc068aa48ac1e7a13ee63227c6622aea654207e9524727b1653b7e4b3bbac9aR1189-R1190
Ref: https://github.com/denoland/deno/pull/28043

build(deps): bring down hickory-proto from 0.25.0-alpha.5 to 0.25.0-alpha.4

---

Cargo.lock

bump ring from 0.17.7 to 0.17.12
ring 0.16.20 is tolerable as it is a dependency of `unsafe-proxy` feature.
https://github.com/supabase/edge-runtime/security/dependabot/53

build(deps): bump ring from 0.17.7 to 0.17.12

---

crates/base/src/runtime/mod.rs

Bug fix
If the main worker passes v1 eszip and entrypoint, the way to handle the base path should be made distinct from v2 eszip.

fix(base): should handle the entrypoint passed from js land correctly

---

crates/base/test_cases/issue-513/deno.json
crates/base/test_cases/issue-513/index.ts
crates/base/tests/integration_tests.rs
crates/deno_facade/module_loader/standalone.rs

Bug fix
Deno now uses a v8 API-based callback approach instead of a heuristic based on stack traces to distinguish the current execution context.
This callback is defined in the ModuleLoader trait and should have been implemented in EmbeddedModuleLoader, but was not. As a result, the current execution context was locked to Deno, which caused it to be unable to get some special keys (global, Buffer, etc...) that only exist on Node.
Fixes #513

fix(deno_facade): implement `get_host_defined_options` member on `EmbeddedModuleLoader`

---

crates/base/test_cases/issue-208/index.ts
crates/base/tests/integration_tests.rs
ext/runtime/js/denoOverrides.js

Bug fix
Exposing `Deno.createHttpClient` since it's stable on Deno 2.x.
Closes #208

fix(ext/runtime): expose `Deno.createHttpClient`

---

crates/base/src/deno_runtime.rs
crates/base/src/worker/supervisor/strategy_per_worker.rs
crates/base/test_cases/issue-func-205/index.ts
crates/base/test_cases/main/index.ts
crates/base/tests/integration_tests.rs
ext/event_worker/events.rs

Bug fix
Triggering `beforeunload` event may cause `Uncaught null` error due to resource limitation.
Closes FUNC-205

fix(base): triggering `beforeunload` event may cause `Uncaught null`

---

ext/ai/utils.rs

Bug fix
The content-length header should not be used because the endpoint might return a response with `transfer-encoding: chunked`.

fix(ai): don't check the content-length header

---

cli/src/flags.rs
cli/src/main.rs

Bug fix
It is easier to mark it as deprecated than to handle it directly in supabase/cli.
Context: https://github.com/supabase/cli/pull/3537

fix: bring back decorator flag in bundle command

---

.github/workflows/ci.yml
rust-toolchain.toml

* do not run CI if PR is marked as draft
* update `rust-toolchain.toml`
*  It looks like clippy and rustfmt are not automatically installed in the `rustup show` command, so I explicitly added these components to the `rust-toolchain.toml`.

fix(ci): update CI

---

Cargo.lock
crates/base/src/runtime/mod.rs
crates/fs/Cargo.toml
crates/fs/impl/prefix_fs.rs
crates/fs/impl/s3_fs.rs
crates/fs/tests/fixture/get/index.ts
crates/fs/tests/fixture/main_with_s3fs/index.ts
crates/fs/tests/integration_tests.rs

Enhancement
This PR allows calling the sync file API using the path with the `/s3` prefix.
Note that the invocation will fail if sync apis are called from inside an async callback.

fix: allow call sync file apis in `/s3` prefix

---

cli/src/env.rs
crates/base/src/deno_runtime.rs

Enhancement
This PR makes it possible to configure the initial/max heap size of main/event worker through environment variables.
* EDGE_RUNTIME_MAIN_WORKER_INITIAL_HEAP_SIZE_MIB
* EDGE_RUNTIME_MAIN_WORKER_MAX_HEAP_SIZE_MIB
* EDGE_RUNTIME_EVENT_WORKER_INITIAL_HEAP_SIZE_MIB
* EDGE_RUNTIME_EVENT_WORKER_MAX_HEAP_SIZE_MIB
To set the heap, you must set both `EDGE_RUNTIME_*_WORKER_INITIAL_HEAP_SIZE_MIB` and `EDGE_RUNTIME_*_WORKER_MAX_HEAP_SIZE_MIB`.
Please note that these values must be set in megabytes.

fix: make initial/max heap size configurable for main/event worker

---

crates/base/src/runtime/mod.rs
crates/base_rt/src/lib.rs
ext/runtime/lib.rs

Bug fix
v8 Isolate has a flag internally to check if a pending interruption request exists, but this flag is recorded as thread-local state, and if Isolate is executed in another thread by a locker, this state does not carry over.
Therefore, in edge-runtime, lines existed to force the interruption flag to be set by calling a dummy interruption request under certain conditions, but when interruptions were requested via op_runtime_metrics, this flag was not set due to a subtle issue.
As a result, the interruption callback was never called and the promise never transitioned to the resolved state.
This PR fixes these issues.

fix: promise returned by `getRuntimeMetrics` never resolved

---

ext/node/ops/os/mod.rs

Bug fix
Comment out `op_geteuid` and `op_getegid` to match the main branch.

fix(ext/node): comment out `op_geteuid` and `op_getegid`

---

crates/base/src/runtime/mod.rs

Bug fix
All scripts initialized in the runtime created by old eszip were specified based on the alternative path reported by `maybe_entrypoint`, not the sanitized virtual path.
These paths can be referenced via import.meta.url, and trying to use this variable to reference specific static files may cause problems.
Because the static files lookup table pointing to the actual specifier of the static file in eszip was also mapped based on sanitized virtual paths, it could not recognize the alternative paths.
This PR adds mapping for alternative paths to the static files lookup table, enabling static files to be referenced properly even in old eszip.

fix: runtime created with the old eszip cannot reference static files properly in some cases

---

crates/base/src/runtime/mod.rs
crates/deno_facade/eszip/migrate.rs
crates/deno_facade/eszip/mod.rs
crates/deno_facade/module_loader/mod.rs
crates/deno_facade/module_loader/standalone.rs
ext/runtime/js/bootstrap.js

Enhancement
If the user created the runtime using old eszip, then print a warning message that they are using an older version.

fix: if runtime is created with old eszip, emit warning message

---

ext/runtime/js/bootstrap.js
types/global.d.ts

Enhancement
Adds an option to suppress the warning added in #581.
Usage:
```typescript
await EdgeRuntime.userWorkers.create({
servicePath,
// ..snip..
context: {
suppressEszipMigrationWarning: true // 👈
}
});
```

fix: add an option that suppresses eszip migration warning

---

.github/workflows/ci.yml

Context: https://supabase.slack.com/archives/C02KMRX22NR/p1755159305940969

chore: add `fail-on-error: false` to coverall upload action

---

crates/base/src/worker/pool.rs
crates/base/src/worker/supervisor/strategy_per_worker.rs
crates/base/test_cases/main/index.ts
crates/base/tests/integration_tests.rs
ext/workers/context.rs
ext/workers/lib.rs
ext/workers/user_workers.js
types/global.d.ts

Feature, Enhancement
Exposes a function that tries to request early drop to idle workers.
Snippet:
```typescript
// ..snip..
EdgeRuntime.userWorkers.tryCleanupIdleWorkers(/* timeout in milliseconds */ 1000);
```

feat: expose a function that tries to clean up idle workers immediately

---

examples/main/index.ts

Bug fix
The main script example explicitly finds the Otel symbol and assigns W3CBaggagePropagator to its propagator key, but if Otel related environment variables are not specified, the Otel symbol may not exist, which could cause TypeError in this line.

fix: Otel symbol may not be exposed in some cases

---

crates/cpu_timer/src/lib.rs

Chore
The cargo check fails on macOS due to issues such as missing cfg attrs, duplicated code, etc.
There is still no v8 library built for macOS, so cargo check still fails, but this issue must be fixed before jumping to up next step.

chore(cpu_timer): cleanup code and place cfg attr correctly

---

crates/base/src/runtime/mod.rs
crates/fs/impl/static_fs.rs
deno/standalone/binary.rs

Bug fix
Node dependencies used in byonm mode may internally attempt to read other files within their own package via the file system API.
This PR enables such attempts.

fix(byonm): Deno.readFile* fails to recognize paths correctly when called from a node package

---

crates/base/src/runtime/mod.rs
crates/base/src/worker/utils.rs
ext/event_worker/events.rs

Enhancement
This PR allows the event worker to get the otel attribute of the user worker that sent the event.
Related to FUNC-289

fix: add `otel_attributes` to event metadata

---

crates/cpu_timer/src/lib.rs

Bug fix
Currently the non linux version of `CPUTimer::new` has a required parameter while the other version don't
Remove the `i64` parameter

fix: CPUTimer wrong `new()` definition for 'non linux' os
